[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Updates to get_blind_amount to account for Miros Bird's effect.
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = '''
self.chips = get_blind_amount(G.GAME.round_resets.ante)*self.mult*G.GAME.starting_params.ante_scaling
'''
position = "at"
payload = '''
self.chips = get_blind_amount(G.GAME.round_resets.ante)*self.mult*G.GAME.starting_params.ante_scaling*G.GAME.mirosbird*G.GAME.mirosvulture
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
local blind_amt = get_blind_amount(G.GAME.round_resets.blind_ante)*blind_choice.config.mult*G.GAME.starting_params.ante_scaling
'''
position = "at"
payload = '''
local blind_amt = get_blind_amount(G.GAME.round_resets.blind_ante)*blind_choice.config.mult*G.GAME.starting_params.ante_scaling*G.GAME.mirosbird*G.GAME.mirosvulture
'''
match_indent = true