[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

#Blind Size Modifier (includes Hugo check)
[[patches]]
[patches.pattern]
target = 'blind.lua'
pattern = '''
self.chips = get_blind_amount(G.GAME.round_resets.ante)*self.mult*G.GAME.starting_params.ante_scaling
'''
position = "after"
payload = '''
if next(SMODS.find_card('j_mxms_hugo')) and self.mult > 1 then
    self.chips = self.chips/self.mult
end
if G.GAME.modifiers.mxms_X_blind_size then
    self.chips = self.chips*G.GAME.modifiers.mxms_X_blind_size
end
if G.GAME.modifiers.mxms_nuclear_size then
    self.chips = self.chips^G.GAME.round_resets.ante
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
local blind_amt = get_blind_amount(G.GAME.round_resets.blind_ante)*blind_choice.config.mult*G.GAME.starting_params.ante_scaling
'''
position = "after"
payload = '''
if next(SMODS.find_card('j_mxms_hugo')) and blind_choice.config.mult > 1 then
    blind_amt = blind_amt/blind_choice.config.mult
end
if G.GAME.modifiers.mxms_X_blind_size then
    blind_amt = blind_amt*G.GAME.modifiers.mxms_X_blind_size
end
if G.GAME.modifiers.mxms_nuclear_size then
    blind_amt = blind_amt^G.GAME.round_resets.ante
end
'''
match_indent = true
times = 1


# All Rare check
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
if polled_rate > check_rate and polled_rate <= check_rate + v.val then
    local card = create_card(v.type, area, nil, nil, nil, nil, nil, 'sho')
'''
position = "at"
payload = '''
if polled_rate > check_rate and polled_rate <= check_rate + v.val then
    local card = nil
    if G.GAME.modifiers.mxms_all_rare and v.type == 'Joker' then
        card = create_card(v.type, area, nil, 0.99, nil, nil, nil, 'sho')
    else
        card = create_card(v.type, area, nil, nil, nil, nil, nil, 'sho')
    end
'''
match_indent = true
times = 1


# Change Matador to not trigger on every hand on Fashion Disaster
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability.name == 'Matador' then
'''
position = "at"
payload = '''
if self.ability.name == 'Matador' and G.GAME.blind.boss then
'''
match_indent = true
times = 2


# Add all faces param check
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
if self.GAME.starting_params.no_faces and SMODS.Ranks[v.value].face then keep = false end
'''
position = "after"
payload = '''
if self.GAME.starting_params.mxms_all_faces and not SMODS.Ranks[v.value].face then keep = false end
'''
match_indent = true
times = 1