[manifest]
version = "1.0.0"
dump_lua = true
priority = 1


[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if v.pinned then _joker.pinned = true end"
position = "after"
payload = "if v.mxms_posted then _joker.ability.mxms_posted = true end"
match_indent = true
times = 1


[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "table.sort(self.cards, function (a, b) return a.T.x + a.T.w/2 - 100*((a.pinned and not a.ignore_pinned) and a.sort_id or 0) < b.T.x + b.T.w/2 - 100*((b.pinned and not b.ignore_pinned) and b.sort_id or 0) end)"
position = "at"
payload = "table.sort(self.cards, function (a, b) return a.T.x + a.T.w/2 - 100*((a.pinned and not a.ignore_pinned or b.ability.mxms_posted and not b.ignore_posted) and a.sort_id or 0) < b.T.x + b.T.w/2 - 100*((b.pinned and not b.ignore_pinned or a.ability.mxms_posted and not a.ignore_posted) and b.sort_id or 0) end)"
match_indent = true
times = 1


[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/ui.lua"]'''
pattern = "card.ignore_pinned = true"
position = "after"
payload = "card.ignore_posted = true"
match_indent = true
times = 1


[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "if v.pinned then card.pinned = true end"
position = "after"
payload = "if v.mxms_posted then card.ability.mxms_posted = true end"
match_indent = true
times = 1