[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#stops loops boss changing colour
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''
if v.boss.showdown then 
'''
position = "at"
payload = '''
if v.boss and v.boss.showdown and G.GAME.round_resets.blind_choices.Boss == "bl_isat_loop_bossblind" then
    return
elseif v.boss and v.boss.showdown then 
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''
elseif eval_type == 'chips' then
'''
position = 'before'
payload = '''
elseif eval_type == 'divmult' then 
	sound = 'isat_divmult'
	amt = amt
	text = 'รท' .. amt .. ' Mult'
	colour = G.C.L_BLACK
	config.type = 'fade'
	config.scale = 0.7
elseif eval_type == 'submult' then 
	sound = 'isat_submult'
	amt = amt
	text = '-' .. amt .. ' Mult'
	colour = G.C.L_BLACK
	config.type = 'fade'
	config.scale = 0.7
'''
match_indent = true

# sfx
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''
sound = extra.edition and 'foil2' or extra.mult_mod and 'multhit1' or extra.Xmult_mod and 'multhit2' or 'generic1'
'''
position = 'at'
payload = '''
sound = extra.edition and 'foil2' or extra.mult_mod and 'multhit1' or extra.Xmult_mod and 'multhit2' or extra.divmult_mod and 'isat_divmult' or extra.submult_mod and 'isat_submult' or 'generic1'
'''
match_indent = true