[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

# generate_UIBox_ability_table
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "bonus_chips = bonus_chips ~= 0 and bonus_chips or nil,"
position = "after"
payload = '''
zero_brights = not not (self.base.suit == "zero_Brights" and not self.config.center.replace_base_card),'''
match_indent = true
overwrite = false

# configure spectrumapi
[[patches]]
[patches.pattern]
target = '=[SMODS SpectrumAPI "main.lua"]'
pattern = '''
function SpectrumAPI.load_content()
'''
position = "after"
payload = '''
		--SpectrumAPI.configuration.misc.spectrums_visible = true
		SpectrumAPI.configuration.misc.spectrum_example_suit = "zero_Brights"
		SpectrumAPI.configuration.misc.specflush_over_spectrum_flush = true
		SpectrumAPI.configuration.hand_types.spa_Flush_Spectrum = true
		SpectrumAPI.configuration.hand_types.spa_Straight_Flush_Spectrum = true
		SpectrumAPI.configuration.hand_types.spa_Flush_Spectrum_House = true
		SpectrumAPI.configuration.hand_types.spa_Flush_Spectrum_Five = true
'''
match_indent = true
overwrite = false