[manifest]
version = "1.0.0"
dump_lua = true
priority = 12

#add more coloumns for ranks to deck view
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''local object = {n = G.UIT.ROOT, config = {align = "cm", colour = G.C.CLEAR}, nodes = {'''
position = "before"
payload = '''
if rank_cols then
    local max_shown = math.max(13,math.ceil(#rank_cols/3))
    local rank_col_1 = {}
    local rank_col_2 = {}
    local rank_col_3 = {}
    local a = #rank_cols + 1
    for i=1, #rank_cols do
        if i > max_shown*2 then 
            rank_col_3[a-i] = rank_cols[a-i]
        elseif i > max_shown then 
            rank_col_2[a-i] = rank_cols[a-i]
        else 
            rank_col_1[a-i] = rank_cols[a-i]
        end
    end

    rank_cols = {{n = G.UIT.C, config = {align = "cm"}, nodes = rank_col_1},
    {n = G.UIT.C, config = {align = "cm"}, nodes = rank_col_2},
    {n = G.UIT.C, config = {align = "cm"}, nodes = rank_col_3}}
end
'''
match_indent = true

