--Slugcats are separated into different files
assert(SMODS.load_file("modules/jokers/abundance.lua"))()
assert(SMODS.load_file("modules/jokers/artificer.lua"))()
assert(SMODS.load_file("modules/jokers/biggreedy.lua"))()
assert(SMODS.load_file("modules/jokers/gourmand.lua"))()
assert(SMODS.load_file("modules/jokers/hunter.lua"))()
assert(SMODS.load_file("modules/jokers/inv.lua"))()
assert(SMODS.load_file("modules/jokers/monk.lua"))()
assert(SMODS.load_file("modules/jokers/rivulet.lua"))()
assert(SMODS.load_file("modules/jokers/saint.lua"))()
assert(SMODS.load_file("modules/jokers/slugpup.lua"))()
assert(SMODS.load_file("modules/jokers/spearmaster.lua"))()
assert(SMODS.load_file("modules/jokers/survivor.lua"))()
assert(SMODS.load_file("modules/jokers/arsenal.lua"))()
assert(SMODS.load_file("modules/jokers/scavenger.lua"))()
assert(SMODS.load_file("modules/jokers/ecoboost.lua"))()
assert(SMODS.load_file("modules/jokers/stupidwetrat.lua"))()
assert(SMODS.load_file("modules/jokers/scavendish.lua"))()
assert(SMODS.load_file("modules/jokers/threat.lua"))()
assert(SMODS.load_file("modules/jokers/surrounded.lua"))()
assert(SMODS.load_file("modules/jokers/familypower.lua"))()
assert(SMODS.load_file("modules/jokers/survival_fittest.lua"))()
assert(SMODS.load_file("modules/jokers/communication.lua"))()
-- Slugcats underneath this line are to be added in the next big update and are unfinished, experimental or in need of cleaning. Uncomment and load them at your own risk!
assert(SMODS.load_file("modules/jokers/pathfinder.lua"))()
assert(SMODS.load_file("modules/jokers/blurred.lua"))()
assert(SMODS.load_file("modules/jokers/scugbo.lua"))()
assert(SMODS.load_file("modules/jokers/alacrity.lua"))()
assert(SMODS.load_file("modules/jokers/magician.lua"))()
assert(SMODS.load_file("modules/jokers/ranger.lua"))()
assert(SMODS.load_file("modules/jokers/enfys.lua"))()
assert(SMODS.load_file("modules/jokers/lacuna.lua"))()
assert(SMODS.load_file("modules/jokers/hungy.lua"))()
--assert(SMODS.load_file("modules/jokers/ploo.lua"))() --doesn't really do anything
