[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.regex]
target = 'functions/common_events.lua'
pattern = 'G\.GAME\.interest_cap/5'
position = 'at'
payload = 'SMODS.get_interest()["interest_cap"]'

[[patches]]
[patches.regex]
target = 'functions/common_events.lua'
pattern = 'vars = \{G\.GAME\.interest_amount, 5'
position = 'at'
payload = 'vars = {G.GAME.interest_amount, SMODS.get_interest()["per_interest"]'

[[patches]]
[patches.regex]
target = 'functions/state_events.lua'
pattern = 'G\.GAME\.interest_cap/5'
position = 'at'
payload = 'SMODS.get_interest()["interest_cap"]'

[[patches]]
[patches.regex]
target = 'functions/state_events.lua'
pattern = 'G\.GAME\.dollars/5'
position = 'at'
payload = 'G.GAME.dollars/SMODS.get_interest()["per_interest"]'