[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
local final_scoring_hand = {}
'''
position = 'after'
payload = '''
local sh_modify_effects = {}
SMODS.calculate_context({force_scoring_hand = true, scoring_hand = G.play.cards}, sh_modify_effects)
for _,v in ipairs(sh_modify_effects) do
    if type(v) == "table" and v.jokers and v.jokers.change_scoring_hand then
        scoring_hand = v.jokers.change_scoring_hand
    end
end
'''
match_indent = true