[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_object.lua"]'''
pattern = '''
hand[self.key] = math.max(hand['s_'..self.key] + hand['l_'..self.key]*(hand.level - 1), 0)
'''
position = "at"
payload = '''
if not next(find_joker('cry-Universum')) then
    hand[self.key] = math.max(hand['s_'..self.key] + hand['l_'..self.key]*(hand.level - 1), 0)
else
    universum_mod = 1
    local effects = {}
    SMODS.calculate_context({cry_universum = true}, effects)
    for i = 1, #effects do
        universum_mod = universum_mod * (effects[i] and effects[i].jokers and effects[i].jokers.mod or 1)
    end
    hand[self.key] = math.max(hand[self.key]* (universum_mod)^amount, hand['s_'..self.key])
end
'''
match_indent = true
