[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.cost = math.max(1, math.floor((self.base_cost + self.extra_cost + 0.5)*(100-G.GAME.discount_percent)/100))"
position = "after"
payload = '''
    if G.GAME.entr_shop_price_modifier then
        self.cost = cry_format(self.cost * G.GAME.entr_shop_price_modifier,'%.2f') end
    if not G.GAME.modifiers.cry_misprint_min and not G.GAME.entr_shop_price_modifier then self.cost = math.floor(self.cost) end
'''
match_indent = true