[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''function love.load()'''
position = "before"
payload = '''
function svrd_format(...)
    return ... 
end
'''
match_indent = true

# initiate variables
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "rental_rate = 3,"
position = "after"
payload = '''
svrd_shop_joker_price_modifier = 1,
'''
match_indent = true

# Fractional pricing from Cryptid
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.cost = math.max(1, math.floor((self.base_cost + self.extra_cost + 0.5)*(100-G.GAME.discount_percent)/100))"
position = "after"
payload = '''
    if self.ability.set == 'Joker' then 
        self.cost = svrd_format(self.cost * G.GAME.svrd_shop_joker_price_modifier,'%.2f') end
    if self.misprint_cost_fac then 
        self.cost = svrd_format(self.cost * self.misprint_cost_fac,'%.2f') 
        if not G.GAME.modifiers.cry_misprint_min then self.cost = math.floor(self.cost) end end
'''
match_indent = true

# Add context for picking booster pack jokers
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "elseif card.ability.set == 'Booster' then"
position = "before"
payload = '''
    playing_card_joker_effects({card})
'''
match_indent = true
