SMODS.Challenge{
    key = 'a7x',
    rules = {
        custom = {
            {id = 'whitelist_hand', value = 'Full House', hand = 'Full House'},
        },
    },
    jokers = {
        {id = 'j_roff_a7x', eternal = true, pinned = false},
    },
    deck = {
        type = 'Challenge Deck',
        cards = {
            { s = "D", r = "A" },
            { s = "D", r = "A" },
            { s = "S", r = "A" },
            { s = "S", r = "A" },
            { s = "C", r = "A" },
            { s = "C", r = "A" },
            { s = "H", r = "A" },
            { s = "H", r = "A" },
            { s = "D", r = "A" },
            { s = "D", r = "A" },
            { s = "S", r = "A" },
            { s = "S", r = "A" },
            { s = "C", r = "A" },
            { s = "C", r = "A" },
            { s = "H", r = "A" },
            { s = "H", r = "A" },
            { s = "D", r = "A" },
            { s = "D", r = "A" },
            { s = "S", r = "A" },
            { s = "S", r = "A" },
            { s = "C", r = "A" },
            { s = "C", r = "A" },
            { s = "H", r = "A" },
            { s = "H", r = "A" },
            { s = "D", r = "A" },
            { s = "D", r = "A" },
            { s = "S", r = "A" },
            { s = "S", r = "A" },
            { s = "C", r = "A" },
            { s = "C", r = "A" },
            { s = "H", r = "A" },
            { s = "H", r = "A" },
            { s = "D", r = "A" },
            { s = "D", r = "A" },
            { s = "S", r = "A" },
            { s = "S", r = "A" },
            { s = "C", r = "A" },
            { s = "C", r = "A" },
            { s = "H", r = "A" },
            { s = "H", r = "A" },
            { s = "H", r = "7" },
            { s = "D", r = "7" },
            { s = "S", r = "7" },
            { s = "C", r = "7" },
            { s = "H", r = "7" },
            { s = "D", r = "7" },
            { s = "S", r = "7" },
            { s = "C", r = "7" },
            { s = "H", r = "7" },
            { s = "D", r = "7" },
            { s = "S", r = "7" },
            { s = "C", r = "7" },
        }
    }
}
