[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Shrouded Sticker functionality

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if v.eternal then _joker:set_eternal(true) end"
position = "after"
match_indent = true
payload = 'if v.shrouded then _joker.ability.chdp_shrouded = true end'

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "if v.eternal then card:set_eternal(true) end"
position = "after"
match_indent = true
payload = 'if v.shrouded then card.ability.chdp_shrouded = true end'

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if G.GAME.modifiers.enable_eternals_in_shop and eternal_perishable_poll > 0.7 then"
position = "before"
match_indent = true
payload = '''
if G.GAME.modifiers.enable_shroudeds_in_shop and pseudorandom((area == G.pack_cards and 'packshr' or 'shrpoll')..G.GAME.round_resets.ante) > 0.8 then
    card.ability.chdp_shrouded = true
end
'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.facing == 'front' then"
position = "before"
match_indent = true
payload = '''
if self.ability.chdp_shrouded == true then
    if self.facing == 'front' then
        self.flipping = 'f2b'
        self.facing = 'back'
        self.pinch.x = true
    end
    return
end
'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Chicot' and G.GAME.blind and G.GAME.blind.boss and not G.GAME.blind.disabled then"
position = "before"
match_indent = true
payload = '''
if self.ability.chdp_shrouded == true then
    self:flip()
end
'''