[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Move back to deck
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "draw_card(G.play,G.discard, it*100/play_count,'down', false, v)"
position = "at"
payload = '''
    if v.ability.gemslot_timecrystal then
        draw_card(G.play,G.deck, it*100/play_count,'down', false, v)
    else
        draw_card(G.play,G.discard, it*100/play_count,'down', false, v)
    end
'''
match_indent = true