-- FILE GENERATED BY JOKER FORGE

-- FILE GENERATED BY JOKER FORGE

SMODS.Joker{ --Dropout
    name = "Dropout",
    key = "dropout",
    config = {
        extra = {
            investment = 0
        }
    },
    loc_txt = {
        ['name'] = 'Dropout',
        ['text'] = {
            [1] = 'Gain a {C:attention}investment tag{} after skipping a {C:attention}big blind{}.'
        }
    },
    cost = 6,
    rarity = 2,
    blueprint_compat = true,
    eternal_compat = true,
    unlocked = true,
    discovered = true,
    atlas = 'rf_jokers',
    pos = {x = 4, y = 4},

    loc_vars = function(self, info_queue, card)
        return {vars = {}}
    end,

    calculate = function(self, card, context)
        if context.skip_blind and not context.blueprint then
            if G.GAME.blind:get_type() == 'Big' then
                return {
                    func = function()
            G.E_MANAGER:add_event(Event({
                func = function()
                    add_tag(Tag("tag_investment"))
                    play_sound('generic1', 0.9 + math.random() * 0.1, 0.8)
                    play_sound('holo1', 1.2 + math.random() * 0.1, 0.4)
                    return true
                end
            }))
                    return true
                end,
                    message = "Get ready for a game changer!"
                }
            end
        end
    end
}