-- FILE GENERATED BY JOKER FORGE
-- ** If you find any bugs, or have suggestions, please report them on the GitHub repository: https://github.com/Jayd-H/joker-forge/issues **

-- FILE GENERATED BY JOKER FORGE

SMODS.Joker{ --Family Tree
    name = "Family Tree",
    key = "familytree",
    config = {
        extra = {
        }
    },
    loc_txt = {
        ['name'] = 'Family Tree',
        ['text'] = {
            [1] = 'Playing a {C:attention}Royal Family{} or {C:attention}Lineage {}creates the {C:spectral}Familiar spectral{} card.'
        }
    },
    pos = {
        x = 0,
        y = 0
    },
    cost = 6,
    rarity = 2,
    blueprint_compat = true,
    eternal_compat = true,
    unlocked = true,
    discovered = true,
    atlas = 'familytree',

    loc_vars = function(self, info_queue, card)
        return {vars = {}}
    end,

    calculate = function(self, card, context)
        if context.cardarea == G.jokers and context.joker_main then
            if (context.scoring_name == "rfCAV_Lineage" or next(context.poker_hands["rfCAV_Royal Family"])) then
                local created_spectral = false
                if #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit then
                    created_spectral = true
                    G.GAME.consumeable_buffer = G.GAME.consumeable_buffer + 1
                    G.E_MANAGER:add_event(Event({
                        func = function()
                            local spectral_card = create_card('Spectral', G.consumeables, nil, nil, nil, nil, nil, 'joker_forge_spectral')
                            spectral_card:add_to_deck()
                            G.consumeables:emplace(spectral_card)
                            G.GAME.consumeable_buffer = 0
                            return true
                        end
                    }))
                end
                return {
                    message = created_spectral and localize('k_plus_spectral') or nil
                }
            end
        end
    end
}