-- FILE GENERATED BY JOKER FORGE
-- ** If you find any bugs, or have suggestions, please report them on the GitHub repository: https://github.com/Jayd-H/joker-forge/issues **

-- FILE GENERATED BY JOKER FORGE

SMODS.Joker{ --Joker.wav
    name = "Joker.wav",
    key = "jokerwav",
    config = {
        extra = {
            juggle = 0,
            odds = 2
        }
    },
    loc_txt = {
        ['name'] = 'Joker.wav',
        ['text'] = {
            [1] = '{C:green}1 in 2{} chance to create a{C:attention} Juggle Tag{} whenever{C:planet}',
            [2] = 'the{} {C:tarot}game\'s{} {C:spectral}music{} {C:dark_edition}changes.{}',
            [3] = '{C:inactive}(Booster Packs and Showdown Blinds){}'
        }
    },
    pos = {
        x = 0,
        y = 0
    },
    cost = 6,
    rarity = 2,
    blueprint_compat = true,
    eternal_compat = true,
    unlocked = true,
    discovered = true,
    atlas = 'jokerwav',

    loc_vars = function(self, info_queue, card)
        return {vars = {}}
    end,

    calculate = function(self, card, context)
        if context.open_booster and not context.blueprint then
                if pseudorandom('group_0_f7b4ce4f') < G.GAME.probabilities.normal / card.ability.extra.odds then
                        SMODS.calculate_effect({func = function()
            G.E_MANAGER:add_event(Event({
                func = function()
                    local tag = Tag("tag_juggle")
                    tag:set_ability()
                    add_tag(tag)
                    play_sound('holo1', 1.2 + math.random() * 0.1, 0.4)
                    return true
                end
            }))
                    return true
                end}, card)
                        card_eval_status_text(context.blueprint_card or card, 'extra', nil, nil, nil, {message = "Created Tag!", colour = G.C.GREEN})
                    end
        end
        if context.setting_blind and not context.blueprint then
            if (G.GAME.blind.boss and G.GAME.round_resets.ante == 8) then
                if pseudorandom('group_0_6b1927bf') < G.GAME.probabilities.normal / card.ability.extra.odds then
                        SMODS.calculate_effect({func = function()
            G.E_MANAGER:add_event(Event({
                func = function()
                    local tag = Tag("tag_juggle")
                    tag:set_ability()
                    add_tag(tag)
                    play_sound('holo1', 1.2 + math.random() * 0.1, 0.4)
                    return true
                end
            }))
                    return true
                end}, card)
                        card_eval_status_text(context.blueprint_card or card, 'extra', nil, nil, nil, {message = "Created Tag!", colour = G.C.GREEN})
                    end
            end
        end
    end
}