-- FILE GENERATED BY JOKER FORGE
-- ** If you find any bugs, or have suggestions, please report them on the GitHub repository: https://github.com/Jayd-H/joker-forge/issues **

-- FILE GENERATED BY JOKER FORGE

SMODS.Joker{ --Terraforming Mars
    name = "Terraforming Mars",
    key = "terraformingmars",
    config = {
        extra = {
            FourofKindCount = 0,
            mars = 0
        }
    },
    loc_txt = {
        ['name'] = 'Terraforming Mars',
        ['text'] = {
            [1] = 'After scoring {C:attention}2{}{C:green} Four of a Kind{},',
            [2] = 'earn a {C:planet}Mars {}{C:planet}Planet{} card for',
            [3] = 'every subsequent hand until the round is over.'
        }
    },
    pos = {
        x = 0,
        y = 0
    },
    cost = 6,
    rarity = 2,
    blueprint_compat = true,
    eternal_compat = true,
    unlocked = true,
    discovered = true,
    atlas = 'rf_jokers',
    pos = {x = 2, y = 1},

    loc_vars = function(self, info_queue, card)
        return {vars = {}}
    end,

    calculate = function(self, card, context)
        if context.cardarea == G.jokers and context.joker_main then
            if context.scoring_name == "Four of a Kind" then
                card.ability.extra.FourofKindCount = (card.ability.extra.FourofKindCount) + 1
            elseif (card.ability.extra.FourofKindCount or 0) == 2 then
                local created_planet = false
                if #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit then
                    created_planet = true
                    G.GAME.consumeable_buffer = G.GAME.consumeable_buffer + 1
                    G.E_MANAGER:add_event(Event({
                        func = function()
                            local planet_card = create_card('Planet', G.consumeables, nil, nil, nil, nil, 'c_mars')
                            planet_card:add_to_deck()
                            G.consumeables:emplace(planet_card)
                            G.GAME.consumeable_buffer = 0
                            return true
                        end
                    }))
                end
                return {
                    message = "Terraformed!"
                }
            end
        end
        if context.end_of_round and context.game_over == false and context.main_eval and not context.blueprint then
                return {
                    func = function()
                    card.ability.extra.FourofKindCount = 0
                    return true
                end,
                    message = "Reset!"
                }
        end
    end
}