[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if self.ability.name == "Brainstorm" then'''
position = 'before'
payload = '''if (self.ability.name == "j_valk_tau_blueprint") then
    if not context.no_blueprint then
        local taubp_extras = {}
        for i = 1, #G.jokers.cards do
            local new_context = {}
            for j, k in pairs(context) do
                new_context[j] = k
            end
            if (G.jokers.cards[i-1] == self) or (G.jokers.cards[i-2] == self) or (G.jokers.cards[i-3] == self) then
                local other_joker = G.jokers.cards[i]
                if (new_context.blueprint or 0) > #G.jokers.cards then return end
                local old_context_blueprint = new_context.blueprint
                new_context.blueprint = (new_context.blueprint and (new_context.blueprint + 1)) or 1
                local old_context_blueprint_card = new_context.blueprint_card
                new_context.blueprint_card = new_context.blueprint_card or self
                local eff_card = new_context.blueprint_card
                local other_joker_ret = other_joker:calculate_joker(new_context)
                new_context.blueprint = old_context_blueprint
                new_context.blueprint_card = old_context_blueprint_card
                if other_joker_ret then
                    other_joker_ret.card = eff_card
                    other_joker_ret.colour = G.C.PURPLE
                    table.insert(taubp_extras, other_joker_ret)
                end
            end
            
        end
        if #taubp_extras > 0 then
            if context.repetition then
                local rep_count = 0
                for i = 1, #taubp_extras do
                    local j = 1
                    local search = taubp_extras[i]
                    while j < 100 do
                        if search.repetitions then
                            rep_count = rep_count + search.repetitions
                        end
                        search = search.extra
                        if (search == nil) or (type(search) ~= 'table') then
                            break
                        end
                    end
                end
                return {
                    message = localize('k_again_ex'),
                    repetitions = rep_count,
                    card = self,
                    colour = G.C.PURPLE
                }
            end
            return {
                taubp_extras = taubp_extras
            }
        end
    end
end'''
match_indent = true