[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """    local card_aligned = 'bm'"""
position = "at"
payload = """    local card_aligned = 'bm'
    if extra and extra.card_align then card_aligned = extra.card_align end
    local card_trigger_before = false
    if extra and extra.card_trigger_before then card_trigger_before = extra.card_trigger_before end
    local card_trigger = 'before'
    if extra and extra.card_trigger then card_trigger = extra.card_trigger end
"""
overwrite = true
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """            G.E_MANAGER:add_event(Event({ --Add bonus chips from this card
                    trigger = 'before',
                    delay = delay,
                    func = function()
                    if extrafunc then extrafunc() end
                    attention_text({
                        text = text,
                        scale = config.scale or 1, 
                        hold = delay - 0.2,
                        backdrop_colour = colour,
                        align = card_aligned,
                        major = card,
                        offset = {x = 0, y = y_off}
                    })
                    play_sound(sound, 0.8+percent*0.2, volume)
                    if not extra or not extra.no_juice then
                        card:juice_up(0.6, 0.1)
                        G.ROOM.jiggle = G.ROOM.jiggle + 0.7
                    end
                    return true
                    end
            }))"""
position = "at"
payload = """            G.E_MANAGER:add_event(Event({ --Add bonus chips from this card
                    trigger = card_trigger,
                    delay = delay,
                    func = function()
                    if extrafunc then extrafunc() end
                    attention_text({
                        text = text,
                        scale = config.scale or 1, 
                        hold = delay - 0.2,
                        backdrop_colour = colour,
                        align = card_aligned,
                        major = card,
                        offset = {x = 0, y = y_off}
                    })
                    play_sound(sound, 0.8+percent*0.2, volume)
                    if not extra or not extra.no_juice then
                        card:juice_up(0.6, 0.1)
                        G.ROOM.jiggle = G.ROOM.jiggle + 0.7
                    end
                    return true
                    end
            }), 'base', card_trigger_before)"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """    if not self.states.focus.is and self.children.focused_ui then"""
position = "before"
payload = """
if self.flipping == 'akyrs_f2b_y' then
    if self.sprite_facing == 'front' or true then
        if self.VT.h <= 0 then
            self.sprite_facing = 'back'
            self.pinch.y =false
        end
    end
end
if self.flipping == 'akyrs_b2f_y' then
    if self.sprite_facing == 'back' or true then
        if self.VT.h <= 0 then
            self.sprite_facing = 'front'
            self.pinch.y =false
        end
    end
end"""
overwrite = true
match_indent = true