[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = """    self.ARGS.invisible_area_types = self.ARGS.invisible_area_types or {discard=1, voucher=1, play=1, consumeable=1, title = 1, title_2 = 1}"""
position = "after"
payload = """
self.ARGS.invisible_area_types["akyrs_credits"] = 1
self.ARGS.invisible_area_types["akyrs_solitaire_foundation"] = 1
self.ARGS.invisible_area_types["akyrs_solitaire_tableau"] = 1
self.ARGS.invisible_area_types["akyrs_solitaire_waste"] = 1
self.ARGS.invisible_area_types["akyrs_cards_temporary_dragged"] = 1
"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = """    self.config.sort = config.sort or 'desc'"""
position = "after"
payload = """
self.config.akyrs_emplace_func = config.akyrs_emplace_func or nil
self.config.akyrs_sol_emplace_func = config.akyrs_sol_emplace_func or nil
self.config.akyrs_pile_drag = config.akyrs_pile_drag or nil
"""
overwrite = true
match_indent = true


[[patches]]
[patches.pattern]
target = "game.lua"
pattern = """            if (not v.parent and v ~= self.CONTROLLER.dragging.target and v ~= self.CONTROLLER.focused.target) then
                love.graphics.push()
                v:translate_container()
                v:draw()
                love.graphics.pop()
            end"""
position = "before"
payload = """
if not v.akyrs_stay_on_top then
"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = """            if (not v.parent and v ~= self.CONTROLLER.dragging.target and v ~= self.CONTROLLER.focused.target) then
                love.graphics.push()
                v:translate_container()
                v:draw()
                love.graphics.pop()
            end"""
position = "after"
payload = """
end
"""
overwrite = true
match_indent = true



[[patches]]
[patches.pattern]
target = "game.lua"
pattern = """    for k, v in pairs(self.I.MOVEABLE) do
        if not v.parent then 
            love.graphics.push()
            v:translate_container()
            v:draw()
            love.graphics.pop()
        end"""
position = "after"
payload = """end"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = """    for k, v in pairs(self.I.MOVEABLE) do"""
position = "after"
payload = """
if not v.akyrs_stay_on_top then
"""
overwrite = true
match_indent = true


[[patches]]
[patches.pattern]
target = "game.lua"
pattern = """    if self.screenwipe then"""
position = "before"
payload = """
for k, v in pairs(self.I.MOVEABLE) do
    if v.akyrs_stay_on_top then
        if not v.parent or not v.parent.akyrs_stay_on_top then
            love.graphics.push()
            v:translate_container()
            v:draw()
            love.graphics.pop()
        end
    end
end
"""
overwrite = true
match_indent = true




[[patches]]
[patches.pattern]
target = "game.lua"
pattern = """
    for k, v in pairs(self.I.POPUP) do
        love.graphics.push()
        v:translate_container()
        v:draw()
        love.graphics.pop()
    end
            """
position = "after"
payload = """
for k, v in pairs(self.I.CARD) do
    if (v.akyrs_stay_on_top) then -- PATCHED BY AIKOYORI :D
        love.graphics.push()
        v:translate_container()
        v:draw()
        love.graphics.pop()
    end
end
"""
overwrite = true
match_indent = true


# thanks SleepyG11
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''for k, v in pairs(self.MOVEABLES) do'''
position = "before"
payload = '''
local __new_moveables = {}
for k, v in pairs(self.MOVEABLES) do
    if not v.REMOVED then table.insert(__new_moveables, v) end
end
self.MOVEABLES = __new_moveables
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = """        table.sort(self.cards, function (a, b) return a.T.x + a.T.w/2 < b.T.x + b.T.w/2 end)"""
position = "at"
payload = """        table.sort(self.cards, function (a, b) return a.T.x + a.T.w/2 - 100*(a.pinned and a.sort_id or 0) < b.T.x + b.T.w/2 - 100*(b.pinned and b.sort_id or 0) end)"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = """                update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})"""
position = "before"
payload = """
if AKYRS.hand_display_mod(self.highlighted,text,disp_text,poker_hands) then
else
"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = """                update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})"""
position = "after"
payload = """
end
"""
overwrite = true
match_indent = true
