[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = '=[SMODS entr "items/misc/seals.lua"]'
pattern = """aikoyori was here"""
position = "before"
payload = """listen to me"""
overwrite = true
match_indent = true
