[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = """        if self.cursor_down.target then """
position = "after"
payload = """
--print("the thing is "..AKYRS.check_type(self.cursor_down.target))
"""
overwrite = true
match_indent = true
