[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = """            self.children.back:draw(overlay)"""
position = "before"
payload = '''
if not AKYRS.back_render_override(self, self.children.back, overlay) then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = """            self.children.back:draw(overlay)"""
position = "after"
payload = '''
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = """            self.children.back:draw_shader('dissolve')"""
position = "before"
payload = '''
if not AKYRS.back_render_override(self, self.children.back) then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/card_draw.lua"]'''
pattern = """            self.children.back:draw_shader('dissolve')"""
position = "after"
payload = '''
end
'''
match_indent = true
