[manifest]
version = "1.2"
dump_lua = true
priority = 100

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """    if amt > 0 or amt < 0 then"""
position = "at"
payload = '''if Talisman and (to_big(amt) > to_big(0) or to_big(amt) < to_big(0)) or amt > 0 or amt < 0 then'''
match_indent = true

# fucing talisman
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = """        if to_big(G.GAME.chips) >= to_big(G.GAME.blind.chips) or G.GAME.current_round.hands_left < 1 then
            G.STATE = G.STATES.NEW_ROUND

        else
            G.STATE = G.STATES.DRAW_TO_HAND
        end"""
position = "before"
payload = """
if not G.GAME.akyrs_mathematics_enabled and not G.GAME.current_round.advanced_blind then"""
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = """        if to_big(G.GAME.chips) >= to_big(G.GAME.blind.chips) or G.GAME.current_round.hands_left < 1 then
            G.STATE = G.STATES.NEW_ROUND

        else
            G.STATE = G.STATES.DRAW_TO_HAND
        end"""
position = "after"
payload = """
end"""
overwrite = true
match_indent = true
# fucking vanilla
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = """        if G.GAME.chips - G.GAME.blind.chips >= 0 or G.GAME.current_round.hands_left < 1 then
            G.STATE = G.STATES.NEW_ROUND

        else
            G.STATE = G.STATES.DRAW_TO_HAND
        end"""
position = "before"
payload = """
if not G.GAME.akyrs_mathematics_enabled and not G.GAME.current_round.advanced_blind then"""
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = """        if G.GAME.chips - G.GAME.blind.chips >= 0 or G.GAME.current_round.hands_left < 1 then
            G.STATE = G.STATES.NEW_ROUND

        else
            G.STATE = G.STATES.DRAW_TO_HAND
        end"""
position = "after"
payload = """
end"""
overwrite = true
match_indent = true