[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
pattern = '''-- TARGET: effects before deck final_scoring_step'''
position = 'after'
payload = '''
for i = 1, #G.GAME.tags do
  G.GAME.tags[i]:apply_to_run({type = 'final_scoring_step'})
end
'''