[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

# thanks aiko
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """   end

    if main_end then 
        desc_nodes[#desc_nodes+1] = main_end 
    end"""
position = "before"
payload = """
    elseif _c.set == 'ComplexityCreep' then
        localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = specific_vars}
"""
overwrite = true
match_indent = true