[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

# Add context for Junk Mail to trigger correctly
# as it normally only triggers for Tags
[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
pattern = '''for i = 1, #G.GAME.tags do
    G.GAME.tags[i]:apply_to_run({type = 'voucher_add'})
end'''
position = 'after'
payload = '''
SMODS.calculate_context{cardarea = G.jokers, mf_add_voucher = true, main_eval=true}
'''

[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
pattern = '''self.cost = math.max(1, math.floor((self.base_cost + self.extra_cost + 0.5)*(100-G.GAME.discount_percent)/100))'''
position = 'before'
payload = '''
self.extra_cost = self.extra_cost + (self.bonus_cost or 0)
'''