[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
pattern = '''G.GAME.current_round.hands_left = G.GAME.round_resets.hands'''
position = 'after'
payload = '''G.GAME.current_round.hands_played = 0'''

[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
pattern = '''G.FUNCS.evaluate_play()'''
position = 'after'
payload = '''G.GAME.current_round.hands_played = G.GAME.current_round.hands_played + 1'''
[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
pattern = '''current_round = {'''
position = 'after'
payload = '''hands_played = 0,'''

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
match_indent = true
pattern = '''ease_chips(0)'''
position = 'before'
payload = '''G.GAME.current_round.hands_played = 0'''