[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
match_indent = true
pattern = '''card = card or _cards[#_cards]'''
position = 'before'
payload = '''
if not card then
  for i = 1, #_cards do
    if _cards[i].seal == "mf_screencap_seal" then
      card = _cards[i]
      break
    end
  end
end
'''