--Table Insert
    table.insert(G.CHALLENGES,#G.CHALLENGES+1,{
    name = 'Tester',
    id = 'c_mod_bb_tester',
     rules = {
        custom = {
        },
        modifiers = {
            {id = 'dollars', value = 0},
            {id = 'discards', value = 100},
            {id = 'hands', value = 10000},
            {id = 'reroll_cost', value = 0},
            {id = 'joker_slots', value = 10},
            {id = 'consumable_slots', value = 5},
            {id = 'hand_size', value = 8},
        }
    },
    jokers = {
        {id = 'j_bb_pride'},
    },
    consumeables = {
    },
    vouchers = {
        {id = 'v_overstock_norm'},
        {id = 'v_overstock_plus'},
        {id = 'v_tarot_merchant'},
    },
    deck = {
        --enhancement = 'm_glass',
        --yes_ranks = {['3'] = true,T = true},
        --no_ranks = {['4'] = true},
        --yes_suits = {S=true},
        --no_suits = {D=true},
        --cards = {{s='D',r='2',g='Gold',},{s='D',r='3',g='Gold',},{s='D',r='4',g='Gold',},{s='D',r='5',g='Gold',},{s='D',r='6',g='Gold',},{s='D',r='7',g='Gold',},{s='D',r='8',g='Gold',},{s='D',r='9',g='Gold',},{s='D',r='T',g='Gold',},{s='D',r='J',g='Gold',},{s='D',r='Q',g='Gold',},{s='D',r='K',g='Gold',},{s='D',r='A',g='Gold',},{s='C',r='2',g='Blue',},{s='C',r='3',g='Blue',},{s='C',r='4',g='Blue',},{s='C',r='5',g='Blue',},{s='C',r='6',g='Blue',},{s='C',r='7',g='Blue',},{s='C',r='8',g='Blue',},{s='C',r='9',g='Blue',},{s='C',r='T',g='Blue',},{s='C',r='J',g='Blue',},{s='C',r='Q',g='Blue',},{s='C',r='K',g='Blue',},{s='C',r='A',g='Blue',},{s='S',r='2',g='Purple',},{s='S',r='3',g='Purple',},{s='S',r='4',g='Purple',},{s='S',r='5',g='Purple',},{s='S',r='6',g='Purple',},{s='S',r='7',g='Purple',},{s='S',r='8',g='Purple',},{s='S',r='9',g='Purple',},{s='S',r='T',g='Purple',},{s='S',r='J',g='Purple',},{s='S',r='Q',g='Purple',},{s='S',r='K',g='Purple',},{s='S',r='A',g='Purple',},},
        type = 'Challenge Deck',
    },
    restrictions = {
        banned_cards = {
            {id = 'j_joker'},
            {id = 'j_greedy_joker'},
            {id = 'j_lusty_joker'},
            {id = 'j_wrathful_joker'},
            {id = 'j_gluttenous_joker'},
            {id = 'j_jolly'},
            {id = 'j_zany'},
            {id = 'j_mad'},
            {id = 'j_crazy'},
            {id = 'j_droll'},
            {id = 'j_sly'},
            {id = 'j_wily'},
            {id = 'j_clever'},
            {id = 'j_devious'},
            {id = 'j_crafty'},
            {id = 'j_half'},
            {id = 'j_stencil'},
            {id = 'j_four_fingers'},
            {id = 'j_mime'},
            {id = 'j_credit_card'},
            {id = 'j_ceremonial'},
            {id = 'j_banner'},
            {id = 'j_mystic_summit'},
            {id = 'j_marble'},
            {id = 'j_loyalty_card'},
            {id = 'j_8_ball'},
            {id = 'j_misprint'},
            {id = 'j_dusk'},
            {id = 'j_raised_fist'},
            {id = 'j_chaos'},
            {id = 'j_fibonacci'},
            {id = 'j_steel_joker'},
            {id = 'j_scary_face'},
            {id = 'j_abstract'},
            {id = 'j_delayed_grat'},
            {id = 'j_hack'},
            {id = 'j_pareidolia'},
            {id = 'j_gros_michel'},
            {id = 'j_even_steven'},
            {id = 'j_odd_todd'},
            {id = 'j_scholar'},
            {id = 'j_business'},
            {id = 'j_supernova'},
            {id = 'j_ride_the_bus'},
            {id = 'j_space'},
            {id = 'j_egg'},
            {id = 'j_burglar'},
            {id = 'j_blackboard'},
            {id = 'j_runner'},
            {id = 'j_ice_cream'},
            {id = 'j_dna'},
            {id = 'j_splash'},
            {id = 'j_blue_joker'},
            {id = 'j_sixth_sense'},
            {id = 'j_constellation'},
            {id = 'j_hiker'},
            {id = 'j_faceless'},
            {id = 'j_green_joker'},
            {id = 'j_superposition'},
            {id = 'j_todo_list'},
            {id = 'j_cavendish'},
            {id = 'j_card_sharp'},
            {id = 'j_red_card'},
            {id = 'j_madness'},
            {id = 'j_square'},
            {id = 'j_seance'},
            {id = 'j_riff_raff'},
            {id = 'j_vampire'},
            {id = 'j_shortcut'},
            {id = 'j_hologram'},
            {id = 'j_vagabond'},
            {id = 'j_baron'},
            {id = 'j_cloud_9'},
            {id = 'j_rocket'},
            {id = 'j_obelisk'},
            {id = 'j_midas_mask'},
            {id = 'j_luchador'},
            {id = 'j_photograph'},
            {id = 'j_gift'},
            {id = 'j_turtle_bean'},
            {id = 'j_erosion'},
            {id = 'j_reserved_parking'},
            {id = 'j_mail'},
            {id = 'j_to_the_moon'},
            {id = 'j_hallucination'},
            {id = 'j_fortune_teller'},
            {id = 'j_juggler'},
            {id = 'j_drunkard'},
            {id = 'j_stone'},
            {id = 'j_golden'},
            {id = 'j_lucky_cat'},
            {id = 'j_baseball'},
            {id = 'j_bull'},
            {id = 'j_diet_cola'},
            {id = 'j_trading'},
            {id = 'j_flash'},
            {id = 'j_popcorn'},
            {id = 'j_trousers'},
            {id = 'j_ancient'},
            {id = 'j_ramen'},
            {id = 'j_walkie_talkie'},
            {id = 'j_selzer'},
            {id = 'j_castle'},
            {id = 'j_smiley'},
            {id = 'j_campfire'},
            {id = 'j_ticket'},
            {id = 'j_mr_bones'},
            {id = 'j_acrobat'},
            {id = 'j_sock_and_buskin'},
            {id = 'j_swashbuckler'},
            {id = 'j_troubadour'},
            {id = 'j_certificate'},
            {id = 'j_smeared'},
            {id = 'j_throwback'},
            {id = 'j_hanging_chad'},
            {id = 'j_rough_gem'},
            {id = 'j_bloodstone'},
            {id = 'j_arrowhead'},
            {id = 'j_onyx_agate'},
            {id = 'j_glass'},
            {id = 'j_ring_master'},
            {id = 'j_flower_pot'},
            {id = 'j_blueprint'},
            {id = 'j_wee'},
            {id = 'j_merry_andy'},
            --{id = 'j_oops'},
            {id = 'j_idol'},
            {id = 'j_seeing_double'},
            {id = 'j_matador'},
            {id = 'j_hit_the_road'},
            {id = 'j_duo'},
            {id = 'j_trio'},
            {id = 'j_family'},
            {id = 'j_order'},
            {id = 'j_tribe'},
            {id = 'j_stuntman'},
            {id = 'j_invisible'},
            {id = 'j_brainstorm'},
            {id = 'j_satellite'},
            {id = 'j_shoot_the_moon'},
            {id = 'j_drivers_license'},
            {id = 'j_cartomancer'},
            {id = 'j_astronomer'},
            {id = 'j_burnt'},
            {id = 'j_bootstraps'},
            {id = 'j_caino'},
            {id = 'j_triboulet'},
            {id = 'j_yorick'},
            {id = 'j_chicot'},
            {id = 'j_perkeo'},
        },
    }
})
--Localization

G.localization.misc.challenge_names["c_mod_bb_tester"] = "Tester"
