# modified directly from Paperback Mod

[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if add and not G.GAME.banned_keys[v.key] then "
position = "after"
match_indent = true
payload = '''
    -- If the selected deck is the Aid deck and this key is a Modded Joker, add copies of it
    -- to the pool, so that it is more common to get
    if (G.GAME.selected_back_key or {}).key == 'b_bb_aid' and v.key:find('j_bb_') then
      for i = 1, 4 do
        _pool[#_pool + 1] = v.key
        _pool_size = _pool_size + 1
      end
    end
    -- make tower and justice more common
    --if (G.GAME.selected_back_key or {}).key == 'b_bb_aid' and v.key:find('c_') then
    --  for i = 1, 20 do
    --    _pool[#_pool + 1] = 'c_justice'
    --    _pool[#_pool + 1] = 'c_tower'
    --    _pool_size = _pool_size + 2
    --  end
    --end
'''
