[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Auxiliary Cards undiscovered sprite, based on Polyminoes undiscovered sprite from Bunco
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''local shared_sprite = (self.ability.set == 'Edition' or self.ability.set == 'Joker') and G.shared_undiscovered_joker or G.shared_undiscovered_tarot'''
position = 'after'
match_indent = true
payload = '''

if not G.shared_undiscovered_auxiliary then G.shared_undiscovered_auxiliary = Sprite(0, 0, G.CARD_W, G.CARD_H, G.ASSET_ATLAS['unstb_auxiliary_undiscovered'], {x = 1, y = 0}) end

if self.ability.set == 'Auxiliary' then
    shared_sprite = G.shared_undiscovered_auxiliary
end

'''